version: '3'
services:
  mongo:
    build: 
      context: .
      dockerfile: Dockerfile.mongo
    ports:
     - "27016:27017"
  web:
    build: .
    ports:
     - "8080:8080"
    env_file:
      - .env
    depends_on: 
     - mongo 
    volumes:
     - ./:/usr/app
     - /usr/app/node_modules
     