version: '3'
services:
  mongo:
    image: mongo:6.0.8
  web:
    build: .
    ports:
     - "8080:8080"
    env_file:
      - .env
    depends_on: 
     - mongo 
    volumes:
     - ./:/usr/app
     - /usr/app/node_modules
     